export const DOCTOR_GET_SYMPTOM_REQUEST = "DOCTOR_GET_SYMPTOM_REQUEST";
export const DOCTOR_GET_SYMPTOM_SUCCESS = "DOCTOR_GET_SYMPTOM_SUCCESS";
export const DOCTOR_GET_SYMPTOM_FAILURE = "DOCTOR_GET_SYMPTOM_FAILURE";
