export const DOCTOR_GET_SYMPTOM_REQUEST = "DOCTOR_GET_SYMPTOM_REQUEST";
export const DOCTOR_GET_SYMPTOM_SUCCESS = "DOCTOR_GET_SYMPTOM_SUCCESS";
export const DOCTOR_GET_SYMPTOM_FAILURE = "DOCTOR_GET_SYMPTOM_FAILURE";

export const DOCTOR_CREATE_BOOKING_REQUEST = "DOCTOR_CREATE_BOOKING_REQUEST";
export const DOCTOR_CREATE_BOOKING_SUCCESS = "DOCTOR_CREATE_BOOKING_SUCCESS";
export const DOCTOR_CREATE_BOOKING_FAILURE = "DOCTOR_CREATE_BOOKING_FAILURE";
