export const USERS_FETCH_ME_REQUEST = "USERS_FETCH_ME_REQUEST";
export const USERS_FETCH_ME_SUCCESS = "USERS_FETCH_ME_SUCCESS";
export const USERS_FETCH_ME_FAILURE = "USERS_FETCH_ME_FAILURE";

export const USERS_REGISTER_REQUEST = "USERS_REGISTER_REQUEST";
export const USERS_REGISTER_SUCCESS = "USERS_REGISTER_SUCCESS";
export const USERS_REGISTER_FAILURE = "USERS_REGISTER_FAILURE";