# Generated by Django 3.0.7 on 2020-06-12 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_symptom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingevent',
            name='doctor',
        ),
        migrations.AddField(
            model_name='bookingevent',
            name='doctors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.BookingRequest'),
        ),
    ]
