# Generated by Django 3.0.7 on 2020-06-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200612_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingevent',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BookingRequest'),
        ),
    ]
